spring.application.name=tema2

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/db_prova
spring.datasource.username=davicassoli
spring.datasource.password=dbpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
